### ISSUE TITLE
Can't find/access the scoreboard

### ISSUE THREAD

**Issue by dookgit** [iDigitalFlame/scorebot-core#3]
Hi

Major noob on anything Django etc, and i've been trying to get ScoreBot working for a while, with not much luck.

I can access the Django admin page OK, and create games etc.   But when i browse to /scoreboard/1/  (The game ID i have)   I get a reply saying "This is Scorebot v3" but it looks like an API response, as opposed to the actual scoreboard view, with teams, services etc (I've seen the scoreboard in action at PvJ in BSidesLV)

Am i doing something stupid here, or am i missing some vital steps to get the scoreboard displaying.

Thanks

**Comment by iDigitalFlame** [comment]
Fixed in the latest commit to 3.3.3, will merge to master
urls.py had "scorebot.api" instead of "scorebot.urls"

**Comment by iDigitalFlame** [comment]
Just merged the code, 3.3 with the fixes is now the "master" branch. Please let me know once this has fixed your issue.

Thanks!

**Comment by dookgit** [comment]
Yeah looks good better, although i was getting 404 errors on the static content (JS & CSS etc)  But i added:

STATICFILES_DIRS = ( os.path.join('scorebot_static'), )

to scorebot.settings and now displays fine.   Unsure if thats a step i missed, or another issue, but...i'm working :)

Thanks for your help.

**Comment by iDigitalFlame** [comment]
Ah, most of our builds do not have this due to that we use Apache to run Scorebot through mod_wsgi (It handles staticfiles itself).

I'll close this ticket, feel free to add any more if you run into any issues. Thanks!
